export const themes = {
  hydrion: {
    name: "Hydrion",
    icon: "Zap",
    background: "bg-gradient-to-br from-[#0f0c29] via-[#302b63] to-[#24243e]",
    sidebar: "bg-[#0b1a33] text-white border-r border-blue-400/10",
    text: "text-blue-300",
    glow: "shadow-[0_0_10px_#00f5ff]",
    hover: "hover:bg-blue-500/20 hover:text-blue-300",
    active: "bg-blue-600/30 text-blue-300 shadow-[0_0_10px_#3b82f6aa]",
    input: "w-full p-3 bg-blue-900/40 border border-blue-600 rounded-md text-blue-100 font-mono",
    inputBorder: "border-blue-600",
    button: "bg-blue-700 text-white px-4 py-2 rounded-md transition-all",
    buttonHover: "hover:bg-blue-800 hover:text-blue-100",
    highlight: "bg-blue-600/40",
  },
  obsidian: {
    name: "Obsidian",
    icon: "Moon",
    background: "bg-gradient-to-br from-[#0a0a0a] to-[#1a1a1a]",
    sidebar: "bg-zinc-900 border-zinc-700 shadow-inner text-white",
    text: "text-neutral-300",
    glow: "shadow-none",
    hover: "hover:bg-neutral-800/40 hover:text-white",
    active: "bg-neutral-700 text-white shadow-inner",
    input: "w-full p-3 bg-zinc-800 border border-zinc-600 rounded-md text-white font-mono",
    inputBorder: "border-zinc-600",
    button: "bg-zinc-700 text-white px-4 py-2 rounded-md transition-all",
    buttonHover: "hover:bg-zinc-600 hover:text-white",
    highlight: "bg-zinc-800/60",
  },
  lumina: {
    name: "Lumina",
    icon: "Sun",
    background: "bg-gradient-to-br from-[#f7f7f7] to-[#e2e8f0]",
    sidebar: "bg-white/60 border-gray-200 shadow-xl text-black",
    text: "text-gray-900",
    glow: "shadow-[0_0_8px_#ccc]",
    hover: "hover:bg-gray-200 hover:text-gray-900",
    active: "bg-gray-300 text-gray-900 shadow",
    input: "w-full p-3 bg-white border border-gray-300 rounded-md text-gray-900 font-mono",
    inputBorder: "border-gray-300",
    button: "bg-gray-300 text-black px-4 py-2 rounded-md transition-all",
    buttonHover: "hover:bg-gray-400 hover:text-black",
    highlight: "bg-gray-300/70",
  },
} as const;

export type Theme = keyof typeof themes;
